### PR TITLE
Master

### PR DESCRIPTION
**Pull request by RogueM**
Fritzing diagram for regular Explorer Hat.

### CODE REVIEW

**Comment by RogueM** [comment]
I'm very new to fritzing but I think I did the Explorer regular correctly, please check.

**Comment by Gadgetoid** [comment]
Explorer HAT looks good, but the Pro has the old artwork. I've got a new artwork version locally which uss the silk asseen on the HAT itself, but I can't figure out how on earth you fixed Input 3! All the connections look good in the parts editor, but it just doesn't work.

**Comment by RogueM** [comment]
on the connection tab, the id is 'input3'... I simply couldn't find a way to change it with the GUI, just edit the .fpz file in your .config/Fritzing/user/ folder, then re-export from within the program.

**Comment by Gadgetoid** [comment]
Yeah, the GUI editor is awful- I did most of the editing manually and used some slightly crazy Python scripts to ( try and ) automate some of the pin creation.

Found the problem; both Input 3 and Input 4 were named "input3" which really didn't help things- a side-effect of my manual tinkering.

I'll accept your PR then update with my version.

**Comment by RogueM** [comment]
yes, I can't say I enjoyed any of what went into doing the part... Fritzing crashes on me a few times too.

feel free to upload your graphics for other pimoroni products somewhere for me, I'm particularly interested in the Hack3r as I'd like to make a schematic of my lab eventually, it's getting a little crazy combining all those bits together :D

**Comment by RogueM** [comment]
and by that I meant the silk screen plate, I'll do the fzpz myself (should be fun... err)!

**Pull request merged**
